In [1]:
from bs4 import BeautifulSoup
from requests import get
import re
from models import (Base, session, Cars, engine)
import multiprocessing

import pandas as pd



faster = ["https://www.otomoto.pl/osobowe?page="+str(page)+"&search%5Badvanced_search_expanded%5D=true" for page in range(2,6000)]

In [2]:
# Dodawanie do bazy danych informacji z konkretnego ogłoszenia
def det(link,ID):

 
        
         

         mymap = {"Oferta od": " ", "Marka pojazdu": " ", "Model pojazdu": " ",
                          "Typ nadwozia": " ", "Generacja": " ", "Kolor": " ","Rodzaj koloru": " ",
                          "Rok produkcji": "", "Przebieg": "", "Pojemność skokowa": "",
                          "Rodzaj paliwa": " ", "Moc": " ", "Skrzynia biegów": " ",
                          "Napęd": " ", "Liczba drzwi": " ", "Liczba miejsc": " ",
                          "Kraj pochodzenia": " ", "Data pierwszej rejestracji w historii pojazdu": " ",
                          "Zarejestrowany w Polsce": " ", "Pierwszy właściciel (od nowości)": " ", "Bezwypadkowy": " ",
                          "Serwisowany w ASO": " ", "Stan": " ","Numer rejestracyjny pojazdu":" ",
                          "Spalanie W Mieście":" ","Spalanie Poza Miastem":" ","Wersja":" ","Emisja":" ",
                          "Okres gwarancji producenta":" ","Pokaż oferty z numerem VIN":" ","Możliwość finansowania":" ",
                          "Leasing": " "}
         

         df = pd.DataFrame(columns=["Oferta od", "Marka pojazdu", "Model pojazdu",
                      "Typ nadwozia", "Generacja", "Kolor" "Rodzaj koloru",
                      "Rok produkcji", "Przebieg", "Pojemność skokowa"
                      "Rodzaj paliwa", "Moc", "Skrzynia biegów",
                      "Napęd", "Liczba drzwi", "Liczba miejsc",
                      "Kraj pochodzenia", "Data pierwszej rejestracji w historii pojazdu",
                      "Zarejestrowany w Polsce", "Pierwszy właściciel (od nowości)", "Bezwypadkowy",
                      "Serwisowany w ASO", "Stan", "Numer rejestracyjny pojazdu",
                      "Spalanie W Mieście", "Spalanie Poza Miastem" , "Wersja", "Emisja",
                      "Okres gwarancji producenta", "Pokaż oferty z numerem VIN",
                      "Możliwość finansowania",
                      "Leasing"])
            
         page = get(link)
        
         bs = BeautifulSoup(page.content, 'html.parser')


         

         marka = bs.find_all(class_="ooa-162vy3d e18eslyg3")

         for info in marka:
    
            for key in mymap:
        
                if bool(re.search(f"{key}", info.get_text())):

                    new = re.sub(f"{key}", r"", info.get_text())
                    mymap[key] = new
            
            
         new_row_df = pd.DataFrame([mymap])

         # Dodawanie nowego wiersza do istniejącego DataFrame za pomocą concat
         df = pd.concat([df, new_row_df], ignore_index=True)
         display(df)

In [3]:
# pobieranie listy ofert i przejscie do kolejnej strony po ich zaladowaniu
def offerlist(url):

     page = get(url)
     bs = BeautifulSoup(page.content, 'html.parser')

     # id ogloszenia

     ID = list(map(lambda x: x.split("data-id=")[1].split("\"")[1], re.findall(r'data-id=["\d]+', str(bs.findAll(class_="ooa-yca59n e1oqyyyi0")))))




     # link do oferty
     linki = re.findall(r'https://www.otomoto.pl/[-\w\d/.]+', str(bs.findAll(target="_self")))

     i = 0
     for link in linki:
        
        det(link,ID)
        
     print(url)   

     if url == "https://www.otomoto.pl/osobowe" :
          
          url = "https://www.otomoto.pl/osobowe?page=2"

     else :

          print(url)
          page = str(int(re.findall(r'\d+', str(re.findall(r'page=\d+', url)))[0]) + 1)

          url = "https://www.otomoto.pl/osobowe?page="+page



     offerlist(url)

In [4]:
page = get("https://www.otomoto.pl/osobowe")

bs = BeautifulSoup(page.content, 'html.parser')

ID = re.findall(r'data-id=["\d]+', str(bs.findAll(class_="ooa-yca59n e1oqyyyi0")))

print(f"HALO {ID}")

offerlist("https://www.otomoto.pl/osobowe")

HALO ['data-id="6120733895"', 'data-id="6118461357"', 'data-id="6121123829"', 'data-id="', 'data-id="6120838670"', 'data-id="6120838608"', 'data-id="6120406122"', 'data-id="6120838751"', 'data-id="6120838790"', 'data-id="992', 'data-id="6119790868"', 'data-id="6119617564"', 'data-id="6118241809"', 'data-id="6120975992"', 'data-id="6120838681"', 'data-id="', 'data-id="6120838718"', 'data-id="6115972188"', 'data-id="6120838726"', 'data-id="6117087634"', 'data-id="6119033632"', 'data-id="6110365129"', 'data-id="6120791965"', 'data-id="6119940924"', 'data-id="6116190302"', 'data-id="6120838406"', 'data-id="6120838624"', 'data-id="6117810086"', 'data-id="6121056646"', 'data-id="6120838420"', 'data-id="6120838662"', 'data-id="6120837956"', 'data-id="6120885090"', 'data-id="6116870247"', 'data-id="6120836645"', 'data-id="']

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Opel,Corsa,Auta miejskie,D (2006-2014),NaN,2011,114 300 km,NaN,87 KM,...,1.4 16V 150 Jahre,,,Tak,,,Czarny,Metalik,1 398 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Firma,Peugeot,3008,SUV,I (2009-2016),NaN,2011,267 000 km,NaN,163 KM,...,Hybrid4,CO299 g/km,,Tak,Tak,,Czarny,Perłowy,1 997 cm3,Hybryda

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Firma,Toyota,Corolla,Kombi,Seria E21 (2019-),NaN,2020,134 700 km,NaN,116 KM,...,1.2 T Comfort,,,Tak,Tak,,Biały,,1 197 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mercedes-Benz,GLE,SUV,W166 (2015-2019),NaN,2017,119 000 km,NaN,333 KM,...,400 4Matic 9G-TRONIC AMG Line,CO2197 g/km,,Tak,,Tak,Czarny,Metalik,2 996 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Chrysler,Voyager,Minivan,III (2001-),NaN,2004,330 000 km,NaN,147 KM,...,2.4 SE,,,Tak,,,Granatowy,,2 429 cm3,Benzyna+LPG

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Firma,Mercedes-Benz,GLA,SUV,,NaN,2018,73 000 km,NaN,122 KM,...,180 7G-DCT Urban,,,Tak,Tak,Tak,Czarny,Metalik,1 595 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Honda,Civic,Kompakt,IX (2011-2017),NaN,2016,133 000 km,NaN,142 KM,...,1.8 Comfort,CO2145 g/km,,Tak,,,Szary,Perłowy,1 798 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Peugeot,308,Kombi,T9 (2014-2021),NaN,2017,176 000 km,NaN,150 KM,...,BlueHDi FAP 150 EAT6 Stop&Start GT-Line Edition,CO2108 g/km,,Tak,,,Niebieski,,1 997 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Toyota,Corolla,Kombi,Seria E21 (2019-),NaN,2023,6 000 km,NaN,98 KM,...,1.8 Hybrid Comfort,,,Tak,,,Żółty,,1 798 cm3,Benzyna+LPG

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Ford,Focus,Kompakt,Mk3 (2010-2018),NaN,2014,289 000 km,NaN,115 KM,...,1.6 TDCi Trend,CO2117 g/km,,Tak,,,Srebrny,Metalik,1 560 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Firma,Peugeot,508,Kombi,I (2010-2018),NaN,2015,210 212 km,NaN,180 KM,...,SW BlueHDi 180 EAT6 Stop&Start GT,CO2118 g/km,,Tak,,,Czarny,Metalik,1 997 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Firma,Mercedes-Benz,GLS,SUV,,NaN,2018,8 000 km,NaN,258 KM,...,350 d 4Matic 9G-TRONIC AMG Line,CO2210 g/km,,Tak,,,Czarny,Metalik,2 987 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Audi,A4,Kombi,B9 (2015-),NaN,2016,216 703 km,NaN,190 KM,...,Avant 2.0 TDI S tronic quattro,,,Tak,,,Czarny,Metalik,1 968 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Ford,Kuga,SUV,II (2012-),NaN,2017,98 000 km,NaN,182 KM,...,1.5 EcoBoost 4x4 ST-Line,CO2173 g/km,,Tak,,,Szary,Metalik,1 498 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Suzuki,Swace,Kombi,,NaN,2023,28 000 km,NaN,98 KM,...,,,,Tak,,,Żółty,,1 798 cm3,Hybryda

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Audi,S8,Sedan,D3 (2002-2010),NaN,2007,169 000 km,NaN,450 KM,...,5.2 FSI Quattro,,,,,,Brązowy,,5 204 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,BMW,Seria 3,Sedan,G20/G21 (2019-),NaN,2023,13 000 km,NaN,150 KM,...,318d M Sport,,,Tak,,,Czarny,Metalik,1 995 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Audi,A4,Sedan,B8 (2007-2015),NaN,2008,118 654 km,NaN,143 KM,...,2.0 TDI,CO2124 g/km,,Tak,,,Biały,Metalik,1 968 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Ford,EDGE,SUV,,NaN,2021,12 000 km,NaN,335 KM,...,,,,Tak,,,Niebieski,Metalik,2 700 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Kodiaq,SUV,,NaN,2019,125 000 km,NaN,240 KM,...,2.0 Bi-TDI 4x4 RS DSG 7os,,,Tak,,,Czerwony,Perłowy,1 968 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Audi,A5,Coupe,8T (2007-2016),NaN,2008,251 000 km,NaN,240 KM,...,3.0 TDI Quattro,CO2173 g/km,,Tak,,,Czarny,Metalik,2 967 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mercedes-Benz,Klasa A,Auta małe,W169 (2004-2012),NaN,2008,246 375 km,NaN,82 KM,...,,,,Tak,,,Srebrny,Metalik,1 992 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mazda,CX-3,SUV,,NaN,2017,81 232 km,NaN,120 KM,...,2.0 Skypassion,,,Tak,,,Inny kolor,Metalik,1 998 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Seat,Toledo,Kompakt,III (2004-2009),NaN,2005,310 000 km,NaN,102 KM,...,,,,Tak,,,Niebieski,,1 595 cm3,Benzyna+LPG

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Opel,Insignia,Kombi,A (2008-2017),NaN,2011,245 000 km,NaN,160 KM,...,2.0 CDTI Sports Tourer Automatik,CO2169 g/km,,Tak,,,Czarny,Perłowy,1 956 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Nissan,Qashqai,SUV,I (2007-2013),NaN,2010,168 000 km,NaN,114 KM,...,1.6 I-Way,CO2155 g/km,,Tak,,,Inny kolor,,1 598 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Maybach,Inny,Sedan,,NaN,2016,429 000 km,NaN,455 KM,...,,,,Tak,,,Niebieski,Metalik,4 663 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Octavia,Kombi,III (2013-),NaN,2020,110 078 km,NaN,115 KM,...,1.6 TDI SCR Ambition,CO2109 g/km,,Tak,,,Srebrny,,1 598 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Citroën,C5,Sedan,III (2008-),NaN,2012,257 511 km,NaN,163 KM,...,HDi 165 FAP Exclusive,CO2129 g/km,,Tak,,,Czarny,Metalik,1 997 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Renault,Clio,Kompakt,III (2005-2012),NaN,2005,170 000 km,NaN,75 KM,...,1.2 16V Authentique,CO2135 g/km,,Tak,,,Niebieski,Metalik,1 149 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mazda,CX-3,SUV,,NaN,2018,48 150 km,NaN,120 KM,...,2.0 Skypassion,CO2137 g/km,,Tak,,,Inny kolor,Metalik,1 998 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Kodiaq,SUV,,NaN,2017,104 245 km,NaN,150 KM,...,,,,Tak,,,Inny kolor,,1 998 cm3,Diesel

https://www.otomoto.pl/osobowe

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mercedes-Benz,Klasa A,Auta małe,W169 (2004-2012),NaN,2008,246 375 km,NaN,82 KM,...,,,,Tak,,,Srebrny,Metalik,1 992 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Seat,Toledo,Kompakt,III (2004-2009),NaN,2005,310 000 km,NaN,102 KM,...,,,,Tak,,,Niebieski,,1 595 cm3,Benzyna+LPG

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mazda,CX-3,SUV,,NaN,2017,81 232 km,NaN,120 KM,...,2.0 Skypassion,,,Tak,,,Inny kolor,Metalik,1 998 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Opel,Insignia,Kombi,A (2008-2017),NaN,2011,245 000 km,NaN,160 KM,...,2.0 CDTI Sports Tourer Automatik,CO2169 g/km,,Tak,,,Czarny,Perłowy,1 956 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Nissan,Qashqai,SUV,I (2007-2013),NaN,2010,168 000 km,NaN,114 KM,...,1.6 I-Way,CO2155 g/km,,Tak,,,Inny kolor,,1 598 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Maybach,Inny,Sedan,,NaN,2016,429 000 km,NaN,455 KM,...,,,,Tak,,,Niebieski,Metalik,4 663 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Octavia,Kombi,III (2013-),NaN,2020,110 078 km,NaN,115 KM,...,1.6 TDI SCR Ambition,CO2109 g/km,,Tak,,,Srebrny,,1 598 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Citroën,C5,Sedan,III (2008-),NaN,2012,257 511 km,NaN,163 KM,...,HDi 165 FAP Exclusive,CO2129 g/km,,Tak,,,Czarny,Metalik,1 997 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Renault,Clio,Kompakt,III (2005-2012),NaN,2005,170 000 km,NaN,75 KM,...,1.2 16V Authentique,CO2135 g/km,,Tak,,,Niebieski,Metalik,1 149 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mazda,CX-3,SUV,,NaN,2018,48 150 km,NaN,120 KM,...,2.0 Skypassion,CO2137 g/km,,Tak,,,Inny kolor,Metalik,1 998 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Kodiaq,SUV,,NaN,2017,104 245 km,NaN,150 KM,...,,,,Tak,,,Inny kolor,,1 998 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Octavia,Kombi,III (2013-),NaN,2014,184 800 km,NaN,140 KM,...,1.4 TSI Ambition,CO2128 g/km,,Tak,,,Czerwony,,1 395 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Audi,Q5,SUV,8R (2008-2016),NaN,2012,158 000 km,NaN,177 KM,...,2.0 TDI Quattro S tronic,CO2159 g/km,,Tak,,,Srebrny,,1 968 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Opel,Astra,Coupe,H (2004-2014),NaN,2006,361 600 km,NaN,140 KM,...,III 1.8 Essentia,CO2175 g/km,,Tak,,,Srebrny,Metalik,1 796 cm3,Benzyna+LPG

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Mercedes-Benz,CLK,Coupe,W209 (2002-),NaN,2003,290 000 km,NaN,163 KM,...,200 Kompressor Elegance,,,Tak,,,Inny kolor,Metalik,1 796 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,BMW,X6,SUV,E71 (2008-2014),NaN,2014,223 000 km,NaN,313 KM,...,xDrive40d M Sport,,,Tak,,,Biały,Metalik,2 993 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Fabia,Kompakt,III (2014-2021),NaN,2020,8 850 km,NaN,95 KM,...,1.0 TSI Style,,,Tak,,,Czerwony,Metalik,999 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Ford,Grand C-MAX,Minivan,,NaN,2012,116 000 km,NaN,115 KM,...,,,,Tak,,,Szary,Metalik,1 560 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Opel,Mokka,SUV,,NaN,2015,157 000 km,NaN,136 KM,...,1.6 CDTI Cosmo S&S 4x4,CO2124 g/km,,Tak,,,Brązowy,,1 598 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Audi,A6,Kombi,C6 (2004-2011),NaN,2009,247 234 km,NaN,190 KM,...,2.7 TDI Multitronic,CO2172 g/km,,Tak,,,Czarny,Metalik,2 698 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Volvo,V40,Kompakt,II (2012-),NaN,2016,196 000 km,NaN,120 KM,...,D2 Drive-E Kinetic,,,Tak,,,Biały,Perłowy,1 969 cm3,Diesel

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Renault,Megane,Kombi,IV (2016-),NaN,2019,50 000 km,NaN,140 KM,...,,,,Tak,,,Srebrny,Metalik,1 333 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Skoda,Fabia,Kombi,II (2007-2014),NaN,2011,202 000 km,NaN,70 KM,...,1.2 HTP Combi Elegance,,,Tak,,,Srebrny,Metalik,1 198 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Chevrolet,Camaro,Auta miejskie,,NaN,2019,60 000 km,NaN,453 KM,...,,,,Tak,,,Biały,,6 162 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Volkswagen,Golf,Kombi,VI (2008-2013),NaN,2010,225 000 km,NaN,105 KM,...,1.2 TSI BlueMotion Technology Comfortline,CO2114 g/km,,Tak,,,Czarny,Metalik,1 197 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Suzuki,Swift,Auta miejskie,V (2010-2017),NaN,2011,227 000 km,NaN,94 KM,...,,,,Tak,,,Srebrny,Metalik,1 242 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Ford,Focus,Kompakt,Mk3 (2010-2018),NaN,2011,168 115 km,NaN,149 KM,...,1.6 EcoBoost Start-Stopp-System Titanium,,,Tak,,,Czerwony,Metalik,1 596 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,Opel,Insignia,Sedan,A (2008-2017),NaN,2013,112 000 km,NaN,180 KM,...,1.6 T Edition,CO2186 g/km,,Tak,,,Srebrny,Metalik,1 598 cm3,Benzyna

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,Wersja,Emisja,Okres gwarancji producenta,Pokaż oferty z numerem VIN,Możliwość finansowania,Leasing,Kolor,Rodzaj koloru,Pojemność skokowa,Rodzaj paliwa
0,Prywatne,BMW,Seria 3,Sedan,G20/G21 (2019-),NaN,2020,44 000 km,NaN,374 KM,...,M340i xDrive sport,,,Tak,,,Czarny,Metalik,2 998 cm3,Benzyna

KeyboardInterrupt:

In [ ]:
    tekst = '''SzczegółyOferta odPrywatnePokaż oferty z numerem 
VINTakMa numer rejestracyjnyTakMarka pojazduFordModel pojazduMondeoGeneracjaMk5 
(2014-)Rok produkcji2015Przebieg146 000 kmPojemność skokowa1 997 cm3Rodzaj paliwaDieselMoc179
KMSkrzynia biegówAutomatycznaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście5
l/100kmTyp nadwoziaKombiEmisja CO2124 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyRodzaj koloruPerłowyKraj
pochodzeniaNiemcyData pierwszej rejestracji w historii pojazdu18 styczeń 2019Numer rejestracyjny pojazduZS945KLZarejestrowany
w PolsceTakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN'''

    mymap = {"Oferta od": " ", "Marka pojazdu": " ", "Model pojazdu": " ",
                          "Typ nadwozia": " ", "Generacja": " ", "Kolor": " ","Rodzaj koloru": " ",
                          "Rok produkcji": "", "Przebieg": "", "Pojemność skokowa": "",
                          "Rodzaj paliwa": " ", "Moc": " ", "Skrzynia biegów": " ",
                          "Napęd": " ", "Liczba drzwi": " ", "Liczba miejsc": " ",
                          "Kraj pochodzenia": " ", "Data pierwszej rejestracji w historii pojazdu": " ",
                          "Zarejestrowany w Polsce": " ", "Pierwszy właściciel (od nowości)": " ", "Bezwypadkowy": " ",
                          "Serwisowany w ASO": " ", "Stan": " ","Numer rejestracyjny pojazdu":" ",
                          "Spalanie W Mieście":" ","Spalanie Poza Miastem":" ","Wersja":" ","Emisja":" ",
                          "Okres gwarancji producenta":" ","Pokaż oferty z numerem VIN":" ","Możliwość finansowania":" ",
                          "Leasing": " "}


    
    tekst = re.sub(r"VIN", "vin", tekst)
    tekst = re.sub(r"ASO", "aso", tekst)
    tekst = re.sub(r"KM", "km", tekst)
    tekst = re.sub(r"CO2", "co2", tekst)

    # Dodajemy spacje przed dużymi literami
    tekst = re.sub(r"(?<!^)(?<!\s)([A-Z])", r" \1", tekst)

    # Przywracamy akronimy na ich miejsce
    tekst = re.sub("vin", "VIN", tekst)
    tekst = re.sub("aso", "ASO", tekst)
    tekst = re.sub("km", "KM", tekst)
    tekst = re.sub(r"co2", "CO2", tekst)
    print(tekst)
    
    for key in mymap:
   
      try:

        pattern = f"{key} [A-Za-z0-9łż]+[ ]?(\B[A-Z])?"
        match = re.search(pattern, tekst)
        info = match.group(0).strip()
        print(info)
      except:
        pass

    
    info = re.sub(r"(?![VIN|ASO]+)(\B[A-Z])", r" \1", tekst)

In [ ]:
page = get("https://www.otomoto.pl/osobowe/oferta/audi-a5-lift-3xsline-177ps-sportback-xenon-skora-quattro-navi-shadowline-19-ID6GedgW.html")
bs = BeautifulSoup(page.content, 'html.parser')

marka = bs.find_all(class_="ooa-162vy3d e18eslyg3")

mymap = {"Oferta od": " ", "Marka pojazdu": " ", "Model pojazdu": " ",
                          "Typ nadwozia": " ", "Generacja": " ", "Kolor": " ","Rodzaj koloru": " ",
                          "Rok produkcji": "", "Przebieg": "", "Pojemność skokowa": "",
                          "Rodzaj paliwa": " ", "Moc": " ", "Skrzynia biegów": " ",
                          "Napęd": " ", "Liczba drzwi": " ", "Liczba miejsc": " ",
                          "Kraj pochodzenia": " ", "Data pierwszej rejestracji w historii pojazdu": " ",
                          "Zarejestrowany w Polsce": " ", "Pierwszy właściciel (od nowości)": " ", "Bezwypadkowy": " ",
                          "Serwisowany w ASO": " ", "Stan": " ","Numer rejestracyjny pojazdu":" ",
                          "Spalanie W Mieście":" ","Spalanie Poza Miastem":" ","Wersja":" ","Emisja":" ",
                          "Okres gwarancji producenta":" ","Pokaż oferty z numerem VIN":" ","Możliwość finansowania":" ",
                          "Leasing": " "}

marka = bs.find_all(class_="ooa-162vy3d e18eslyg3")

for info in marka:
    
    for key in mymap:
        
            if bool(re.search(f"{key}", info.get_text())):

                new = re.sub(f"{key}", r"", info.get_text())
                mymap[key] = new
print(mymap)