In [1]:
from bs4 import BeautifulSoup
from requests import get
import re
from models import (Base, session, Cars, engine)
import multiprocessing

import pandas as pd



faster = ["https://www.otomoto.pl/osobowe?page="+str(page)+"&search%5Badvanced_search_expanded%5D=true" for page in range(2,6000)]

In [2]:
# Dodawanie do bazy danych informacji z konkretnego ogłoszenia
def det(link,ID):

 
        
         

         mymap = {"Oferta od": " ", "Marka pojazdu": " ", "Model pojazdu": " ",
                          "Typ nadwozia": " ", "Generacja": " ", "Kolor": " ","Rodzaj koloru": " ",
                          "Rok produkcji": "", "Przebieg": "", "Pojemność skokowa": "",
                          "Rodzaj paliwa": " ", "Moc": " ", "Skrzynia biegów": " ",
                          "Napęd": " ", "Liczba drzwi": " ", "Liczba miejsc": " ",
                          "Kraj pochodzenia": " ", "Data pierwszej rejestracji w historii pojazdu": " ",
                          "Zarejestrowany w Polsce": " ", "Pierwszy właściciel (od nowości)": " ", "Bezwypadkowy": " ",
                          "Serwisowany w ASO": " ", "Stan": " ","Numer rejestracyjny pojazdu":" ",
                          "Spalanie W Mieście":" ","Spalanie Poza Miastem":" ","Wersja":" ","Emisja":" ",
                          "Okres gwarancji producenta":" ","Pokaż oferty z numerem VIN":" ","Możliwość finansowania":" ",
                          "Leasing": " "}
         

         df = pd.DataFrame(columns=["Oferta od", "Marka pojazdu", "Model pojazdu",
                      "Typ nadwozia", "Generacja", "Kolor" "Rodzaj koloru",
                      "Rok produkcji", "Przebieg", "Pojemność skokowa"
                      "Rodzaj paliwa", "Moc", "Skrzynia biegów",
                      "Napęd", "Liczba drzwi", "Liczba miejsc",
                      "Kraj pochodzenia", "Data pierwszej rejestracji w historii pojazdu",
                      "Zarejestrowany w Polsce", "Pierwszy właściciel (od nowości)", "Bezwypadkowy",
                      "Serwisowany w ASO", "Stan", "Numer rejestracyjny pojazdu",
                      "Spalanie W Mieście", "Spalanie Poza Miastem" , "Wersja", "Emisja",
                      "Okres gwarancji producenta", "Pokaż oferty z numerem VIN",
                      "Możliwość finansowania",
                      "Leasing"])
         page = get(link)
        
         details = BeautifulSoup(page.content, 'html.parser')


         offer = details.find(class_="ooa-w4tajz e18eslyg0")

         #print(offer.get_text())
         for key in mymap.keys():
             # Utwórz wzorzec regex, który szuka klucza i wszystkiego po nim do następnego dużego klucza (rozpoczynającego się od wielkiej litery)
             pattern =  f"{key}(.*?)(?=(?:{'|'.join(map(re.escape, mymap.keys()))}|$))"
             match = re.search(pattern, offer.get_text().replace("Kup ten pojazd na ratyObliczVINWyświetl VIN", "")
                               .replace("Pokaż oferty z numerem VINTakMa numer rejestracyjnyTak","")
                               .replace("14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych",""))
             if match:
                 mymap[key] = match.group(1).strip()


         print( offer.get_text())
         info = re.sub(r"(\B[A-Z])", r" \1", offer.get_text())

         
         exit()

         for i in range(0,len(info)-1,2):

             mymap[info[i]]=info[i+1]
            
            
         new_row_df = pd.DataFrame([mymap])

         # Dodawanie nowego wiersza do istniejącego DataFrame za pomocą concat
         df = pd.concat([df, new_row_df], ignore_index=True)
         display(df)

In [3]:
# pobieranie listy ofert i przejscie do kolejnej strony po ich zaladowaniu
def offerlist(url):

     page = get(url)
     bs = BeautifulSoup(page.content, 'html.parser')

     # id ogloszenia

     ID = list(map(lambda x: x.split("data-id=")[1].split("\"")[1], re.findall(r'data-id=["\d]+', str(bs.findAll(class_="ooa-yca59n e1oqyyyi0")))))




     # link do oferty
     linki = re.findall(r'https://www.otomoto.pl/[-\w\d/.]+', str(bs.findAll(target="_self")))

     i = 0
     for link in linki:
        print(f"gej {i+1}")
        det(link,ID)
        
     print(url)   

     if url == "https://www.otomoto.pl/osobowe" :
          
          url = "https://www.otomoto.pl/osobowe?page=2"

     else :

          print(url)
          page = str(int(re.findall(r'\d+', str(re.findall(r'page=\d+', url)))[0]) + 1)

          url = "https://www.otomoto.pl/osobowe?page="+page



     offerlist(url)

In [4]:
page = get("https://www.otomoto.pl/osobowe")

bs = BeautifulSoup(page.content, 'html.parser')

ID = re.findall(r'data-id=["\d]+', str(bs.findAll(class_="ooa-yca59n e1oqyyyi0")))

print(f"HALO {ID}")

offerlist("https://www.otomoto.pl/osobowe")



print(list(map(lambda x: x.split("data-id=")[1].split("\"")[1],ID)))

HALO ['data-id="6119660694"', 'data-id="6113588191"', 'data-id="6120740028"', 'data-id="', 'data-id="6120977273"', 'data-id="6120977270"', 'data-id="6120977266"', 'data-id="6120953891"', 'data-id="6120965386"', 'data-id="1', 'data-id="6120977254"', 'data-id="6120977262"', 'data-id="6120977252"', 'data-id="6119931216"', 'data-id="6120740048"', 'data-id="', 'data-id="6120740031"', 'data-id="6118702708"', 'data-id="6120740011"', 'data-id="6119704178"', 'data-id="6119697275"', 'data-id="6099659141"', 'data-id="6110206816"', 'data-id="6119930689"', 'data-id="6120739962"', 'data-id="6117646744"', 'data-id="6119697477"', 'data-id="6115254017"', 'data-id="6118432763"', 'data-id="6114444482"', 'data-id="6119930569"', 'data-id="6120976243"', 'data-id="6120830017"', 'data-id="6120739954"', 'data-id="6120977082"', 'data-id="']
gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduToyotaModel pojazduAurisWersja1.8 VVT-i Hybrid Automatik ComfortGeneracjaII (2012-)Rok produkcji2017Przebieg85 970 kmPojemność skokowa1 798 cm3Rodzaj paliwaHybrydaMoc99 KMSkrzynia biegówAutomatycznaSpalanie W Mieście3,40 l/100kmTyp nadwoziaKombiLiczba drzwi5Liczba miejsc5KolorBrązowyStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,R,H,b,K,l,W,",",B,ą,ż
0,Prywatne,Toyota,Auris,Kombi,II (2012-),NaN,2017,85 970 km,NaN,99 KM,...,o,y,i,o,,,4,r,z,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduFordModel pojazduMondeoGeneracjaMk5 (2014-)Rok produkcji2015Przebieg146 000 kmPojemność skokowa1 997 cm3Rodzaj paliwaDieselMoc179 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście5 l/100kmTyp nadwoziaKombiEmisja CO2124 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyRodzaj koloruPerłowyKraj pochodzeniaNiemcyData pierwszej rejestracji w historii pojazdu18 styczeń 2019Numer rejestracyjny pojazduZS945KLZarejestrowany w PolsceTakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,W,E,L,h,s,8,ń,Z,B,U
0,Prywatne,Ford,Mondeo,Kombi,Mk5 (2014-),NaN,2015,146 000 km,NaN,179 KM,...,y,m,,o,o,,,a,e,ż

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduBMWModel pojazduX5Wersja3.5d xDriveGeneracjaE70 (2006-2013)Rok produkcji2009Przebieg182 000 kmPojemność skokowa2 993 cm3Rodzaj paliwaDieselMoc286 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie W Mieście10 l/100kmTyp nadwoziaSUVLiczba drzwi5Liczba miejsc7KolorCzarnyRodzaj koloruMetalikKraj pochodzeniaNiemcyData pierwszej rejestracji w historii pojazdu29 grudzień 2009Numer rejestracyjny pojazduSRBEP58Zarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,4,(,ł,),l,s,C,h,ń,U
0,Prywatne,BMW,X5,SUV,E70 (2006-2013),NaN,2009,182 000 km,NaN,286 KM,...,,s,y,S,s,t,z,i,,ż

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduBMWModel pojazduM5WersjaStandardRok produkcji2006Przebieg116 200 kmPojemność skokowa4 999 cm3Rodzaj paliwaBenzynaMoc507 KMSkrzynia biegówAutomatycznaNapędNa tylne kołaSpalanie Poza Miastem10.0 l/100kmSpalanie W Mieście22 l/100kmTyp nadwoziaSedanEmisja CO2361 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyData pierwszej rejestracji w historii pojazdustyczeń 2006Numer rejestracyjny pojazduWR506FXStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,B,l,/,L,s,U,g,ł,ą
0,Prywatne,BMW,M5,Sedan,,NaN,2006,116 200 km,NaN,507 KM,...,,e,/,k,i,t,ż,ó,o,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduVolkswagenModel pojazduNew BeetleWersja1.6Rok produkcji2004Przebieg317 000 kmPojemność skokowa1 595 cm3Rodzaj paliwaBenzyna+LPGMoc102 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem6.0 l/100kmSpalanie W Mieście10 l/100kmTyp nadwoziaAuta małeEmisja CO2185 g/kmLiczba drzwi2Liczba miejsc4KolorSzaryRodzaj koloruMetalikKraj pochodzeniaNiemcyData pierwszej rejestracji w historii pojazdu28 maj 2004Numer rejestracyjny pojazduCLI UX47Zarejestrowany w PolsceTakBezwypadkowyTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,W,ł,C,5,4,R,h,D,8,ż
0,Prywatne,Volkswagen,New Beetle,Auta małe,,NaN,2004,317 000 km,NaN,102 KM,...,,e,,,7,o,o,a,,y

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduFordModel pojazduC-MAXWersja1.6 TDCi GhiaGeneracjaI (2003-2010)Rok produkcji2008Przebieg270 000 kmPojemność skokowa1 560 cm3Rodzaj paliwaDieselMoc109 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem3.0 l/100kmSpalanie W Mieście5 l/100kmTyp nadwoziaAuta miejskieEmisja CO2119 g/kmLiczba drzwi5Liczba miejsc5KolorSrebrnyData pierwszej rejestracji w historii pojazdu03 wrzesień 2008Numer rejestracyjny pojazduDTR 63826StanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,w,b,ł,ś,5,9,8,ż,4,ą
0,Prywatne,Ford,C-MAX,Auta miejskie,I (2003-2010),NaN,2008,270 000 km,NaN,109 KM,...,a,a,y,c,,,2,y,,

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduBMWModel pojazduX5WersjaxDrive25dGeneracjaF15 (2013-2018)Rok produkcji2014Przebieg127 000 kmPojemność skokowa1 995 cm3Rodzaj paliwaDieselMoc218 KMSkrzynia biegówAutomatycznaNapędNa tylne kołaSpalanie Poza Miastem5.0 l/100kmSpalanie W Mieście6 l/100kmTyp nadwoziaSUVEmisja CO2149 g/kmLiczba drzwi5KolorCzarnyKraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdupaździernik 2014Numer rejestracyjny pojazduKWI 97927Zarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,E,4,L,K,C,h,ź,7,I,ś
0,Firma,BMW,X5,SUV,F15 (2013-2018),NaN,2014,127 000 km,NaN,218 KM,...,m,9,i,u,z,i,d,9,,w

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMarka pojazduJeepModel pojazduCompassWersja2.0 MJD Limited 4WD S&SRok produkcji2017Przebieg129 500 kmPojemność skokowa1 956 cm3Rodzaj paliwaDieselMoc140 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie Poza Miastem5.0 l/100kmSpalanie W Mieście7 l/100kmTyp nadwoziaSUVEmisja CO2166 g/kmLiczba drzwi5KolorSzaryStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,A,ę,(,ł,),T,U,V,I,N
0,Firma,Jeep,Compass,SUV,,NaN,2017,129 500 km,NaN,140 KM,...,u,d,s,y,S,y,ż,,,

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduVolvoModel pojazduXC 90WersjaD5 AWD R-DesignGeneracjaII (2014-)Rok produkcji2017Przebieg99 000 kmPojemność skokowa1 969 cm3Rodzaj paliwaDieselMoc235 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany automatycznie)Spalanie Poza Miastem5.0 l/100kmSpalanie W Mieście6 l/100kmTyp nadwoziaSUVEmisja CO2149 g/kmLiczba drzwi5KolorBiałyKraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdu22 lipiec 2017Numer rejestracyjny pojazduPKR 37440Zarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ę,ą,6,ł,h,7,U,b,N,W
0,Firma,Volvo,XC 90,SUV,II (2014-),NaN,2017,99 000 km,NaN,235 KM,...,d,c,,y,i,4,ż,l,,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduVolkswagenModel pojazduPassatWersja2.0 TDI HighlineGeneracjaB6 (2005-2010)Rok produkcji2009Przebieg195 000 kmPojemność skokowa1 968 cm3Rodzaj paliwaDieselMoc140 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście7 l/100kmTyp nadwoziaKombiEmisja CO2153 g/kmLiczba drzwi5Liczba miejsc5KolorSzaryRodzaj koloruMetalikBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,D,K,ę,/,W,E,L,A,ż
0,Prywatne,Volkswagen,Passat,Kombi,B6 (2005-2010),NaN,2009,195 000 km,NaN,140 KM,...,,i,o,d,k,,m,i,,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduPeugeotModel pojazdu208Wersja1.5 BlueHDi Active S&SGeneracjaI (2012-2019)Rok produkcji2020Przebieg96 928 kmPojemność skokowa1 499 cm3Rodzaj paliwaDieselMoc102 KMSkrzynia biegówManualnaTyp nadwoziaAuta miejskieLiczba drzwi5KolorBiałyZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,R,K,A,L,b,5,B,Z,ż
0,Prywatne,Peugeot,208,Auta miejskie,I (2012-2019),NaN,2020,96 928 km,NaN,102 KM,...,,o,o,u,i,a,,i,a,y

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduVolvoModel pojazduXC 60WersjaD4 SCR AWD R-DesignGeneracjaII (2017-)Rok produkcji2018Przebieg126 000 kmPojemność skokowa1 969 cm3Rodzaj paliwaDieselMoc190 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany automatycznie)Spalanie Poza Miastem5.0 l/100kmSpalanie W Mieście6 l/100kmTyp nadwoziaSUVEmisja CO2144 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyKraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdu21 maj 2018Numer rejestracyjny pojazduSZA6410CZarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,/,W,U,E,4,L,5,K,h,ś
0,Firma,Volvo,XC 60,SUV,II (2017-),NaN,2018,126 000 km,NaN,190 KM,...,k,y,ż,m,4,i,,u,o,w

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduAudiModel pojazduA4Wersja2.0 TDI Quattro Sport S tronicGeneracjaB9 (2015-)Rok produkcji2020Przebieg39 400 kmPojemność skokowa1 968 cm3Rodzaj paliwaDieselMoc190 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie Poza Miastem4.0 l/100kmSpalanie W Mieście5 l/100kmTyp nadwoziaKombiEmisja CO2116 g/kmLiczba drzwi5Liczba miejsc5KolorNiebieskiKraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdu23 wrzesień 2020Numer rejestracyjny pojazduWG9290JZarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,l,b,C,6,N,h,G,J,Z,V
0,Firma,Audi,A4,Kombi,B9 (2015-),NaN,2020,39 400 km,NaN,190 KM,...,,i,,,u,o,9,,a,

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMarka pojazduPeugeotModel pojazdu5008Wersja2.0 BlueHDI Crossway S&S EAT8GeneracjaII (2017-)Rok produkcji2019Przebieg132 081 kmPojemność skokowa1 997 cm3Rodzaj paliwaDieselMoc180 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaTyp nadwoziaSUVLiczba drzwi5KolorCzarnyKraj pochodzeniaPolskaZarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,M,b,N,ł,U,V,L,K,W,ś
0,Firma,Peugeot,5008,SUV,II (2017-),NaN,2019,132 081 km,NaN,180 KM,...,o,l,,a,ż,,i,u,y,w

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduHondaModel pojazduAccordGeneracjaX (2018-)Rok produkcji2018Przebieg90 000 kmPojemność skokowa1 500 cm3Rodzaj paliwaBenzynaMoc200 KMSkrzynia biegówAutomatycznaUszkodzonyTakTyp nadwoziaSedanLiczba drzwi4KolorBordowyData pierwszej rejestracji w historii pojazdustyczeń 2018Numer rejestracyjny pojazduwwStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,b,U,L,4,K,l,D,s,p,ż
0,Prywatne,Honda,Accord,Sedan,X (2018-),NaN,2018,90 000 km,NaN,200 KM,...,a,s,i,,o,,a,t,o,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduLand RoverModel pojazduRange RoverWersja3.6TD V8 Vogue SEGeneracjaIII (2001-2012)Rok produkcji2010Przebieg270 000 kmPojemność skokowa3 628 cm3Rodzaj paliwaDieselMoc272 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany automatycznie)Spalanie Poza Miastem9.0 l/100kmSpalanie W Mieście14 l/100kmTyp nadwoziaSUVEmisja CO2294 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,x,ł,/,W,4,C,5,K,U,ś
0,Prywatne,Land Rover,Range Rover,SUV,III (2001-2012),NaN,2010,270 000 km,NaN,272 KM,...,4,ą,1,y,,z,,u,ż,w

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduFordModel pojazduFocusWersjaSTGeneracjaMk3 (2010-2018)Rok produkcji2014Przebieg166 000 kmPojemność skokowa1 999 cm3Rodzaj paliwaBenzynaMoc250 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem5.0 l/100kmSpalanie W Mieście9 l/100kmTyp nadwoziaKompaktEmisja CO2169 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyRodzaj koloruMetalikKraj pochodzeniaSzwajcariaData pierwszej rejestracji w historii pojazdu15 sierpień 2014Numer rejestracyjny pojazduga00000StanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,B,5,ł,C,g,K,h,ń,ż
0,Prywatne,Ford,Focus,Kompakt,Mk3 (2010-2018),NaN,2014,166 000 km,NaN,250 KM,...,,e,,a,z,a,o,i,,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduVolkswagenModel pojazduGolfWersja1.6 TDI (BlueMotion Technology) ComfortlineGeneracjaVII (2012-2020)Rok produkcji2018Przebieg111 770 kmPojemność skokowa1 598 cm3Rodzaj paliwaDieselMoc115 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem3.8 l/100kmSpalanie W Mieście4,70 l/100kmTyp nadwoziaKompaktEmisja CO2111 g/kmLiczba drzwi5Liczba miejsc5KolorCzerwonyRodzaj koloruMetalikKraj pochodzeniaNiemcyData pierwszej rejestracji w historii pojazdu12 grudzień 2018Numer rejestracyjny pojazduSZA6245FZarejestrowany w PolsceTakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,L,5,R,h,D,Z,A,F,U,W
0,Prywatne,Volkswagen,Golf,Kompakt,VII (2012-2020),NaN,2018,111 770 km,NaN,115 KM,...,i,,o,o,a,a,6,,ż,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduChevroletModel pojazduCruzeWersja1.8 LTZ+Rok produkcji2013Przebieg184 539 kmPojemność skokowa1 796 cm3Rodzaj paliwaBenzynaMoc141 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem5.0 l/100kmSpalanie W Mieście8 l/100kmTyp nadwoziaKompaktEmisja CO2155 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyRodzaj koloruMetalikKraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdu15 styczeń 2014Numer rejestracyjny pojazduEL5CT47Zarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,L,b,R,D,ń,C,7,Z,A,ż
0,Prywatne,Chevrolet,Cruze,Kompakt,,NaN,2013,184 539 km,NaN,141 KM,...,i,a,o,a,,,,a,,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduVolkswagenModel pojazduGolfWersja1.4 GTE Plug-In-Hybrid DSGGeneracjaVII (2012-2020)Rok produkcji2015Przebieg274 000 kmPojemność skokowa1 395 cm3Rodzaj paliwaHybrydaMoc150 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaTyp nadwoziaKompaktEmisja CO236 g/kmLiczba drzwi5Liczba miejsc5KolorBiałyRodzaj koloruMetalikKraj pochodzeniaHolandiaData pierwszej rejestracji w historii pojazdu28 maj 2015Numer rejestracyjny pojazduZDR48885Zarejestrowany w PolsceTak Pierwszy właściciel (od nowości)TakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN13 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,b,5,ł,H,h,Z,R,8,ż,ą
0,Prywatne,Volkswagen,Golf,Kompakt,VII (2012-2020),NaN,2015,274 000 km,NaN,150 KM,...,a,,y,o,,,4,5,y,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduVolkswagenModel pojazduGolfWersja1.4 TSI BlueMotion Technology CupGeneracjaVII (2012-2020)Rok produkcji2014Przebieg235 146 kmPojemność skokowa1 395 cm3Rodzaj paliwaBenzynaMoc125 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie W Mieście6,70 l/100kmTyp nadwoziaKompaktLiczba drzwi5Liczba miejsc5KolorSzaryKraj pochodzeniaNiemcyBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,5,6,ś,w,3,ł,",",K,h,U
0,Prywatne,Volkswagen,Golf,Kompakt,VII (2012-2020),NaN,2014,235 146 km,NaN,125 KM,...,,,w,a,,a,7,u,o,ż

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduPeugeotModel pojazduInnyRok produkcji1966Przebieg50 523 kmPojemność skokowa1 468 cm3Rodzaj paliwaBenzynaMoc52 KMSkrzynia biegówManualnaNapędNa przednie kołaTyp nadwoziaMinivanLiczba drzwi4KolorNiebieskiKraj pochodzeniaFrancjaStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,w,ł,v,L,4,K,h,U,W,ś
0,Prywatne,Peugeot,Inny,Minivan,,NaN,1966,50 523 km,NaN,52 KM,...,i,a,a,i,,u,o,ż,y,w

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduAudiModel pojazduQ3Rok produkcji2017Przebieg75 000 kmPojemność skokowa1 984 cm3Rodzaj paliwaBenzynaMoc220 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaSpalanie W Mieście10 l/100kmTyp nadwoziaSUVLiczba drzwi5Liczba miejsc5KolorSrebrnyRodzaj koloruMetalikKraj pochodzeniaStany ZjednoczoneZarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,R,B,b,ł,W,s,K,h,U
0,Prywatne,Audi,Q3,SUV,,NaN,2017,75 000 km,NaN,220 KM,...,,o,e,l,a,y,o,u,o,ż

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduKiaModel pojazduCeedWersja1.4 MGeneracjaIII (2018-)Rok produkcji2018Przebieg57 000 kmPojemność skokowa1 368 cm3Rodzaj paliwaBenzynaMoc100 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście7 l/100kmUszkodzonyTakTyp nadwoziaKombiEmisja CO2139 g/kmLiczba drzwi5Liczba miejsc5KolorSzaryRodzaj koloruMetalikData pierwszej rejestracji w historii pojazdu05 maj 2018Numer rejestracyjny pojazduwwStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ł,s,U,K,E,/,L,5,h,ż
0,Prywatne,Kia,Ceed,Kombi,III (2018-),NaN,2018,57 000 km,NaN,100 KM,...,a,t,s,o,m,k,i,,i,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduBMWModel pojazduSeria 3GeneracjaF30/F31 (2012-2020)Rok produkcji2015Przebieg259 000 kmPojemność skokowa1 995 cm3Rodzaj paliwaDieselMoc184 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Typ nadwoziaKombiLiczba drzwi5Liczba miejsc5KolorBiałyRodzaj koloruPerłowyKraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdu18 czerwiec 2015Numer rejestracyjny pojazduEL6J798Zarejestrowany w PolsceTak Pierwszy właściciel (od nowości)TakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN13 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ł,),L,l,s,h,6,J,ż,ą
0,Prywatne,BMW,Seria 3,Kombi,F30/F31 (2012-2020),NaN,2015,259 000 km,NaN,184 KM,...,y,T,i,,z,,,7,y,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduOpelModel pojazduZafiraWersjaTourer 2.0 CDTI Automatik Business InnovationGeneracjaC (2011-2019)Rok produkcji2019Przebieg133 647 kmPojemność skokowa1 956 cm3Rodzaj paliwaDieselMoc170 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaSpalanie W Mieście7,50 l/100kmTyp nadwoziaMinivanLiczba drzwi5Liczba miejsc7KolorInny kolorRodzaj koloruMetalikKraj pochodzeniaNiemcyBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ć,5,l,w,7,b,ł,",",K,ż
0,Prywatne,Opel,Zafira,Minivan,C (2011-2019),NaN,2019,133 647 km,NaN,170 KM,...,,6,,i,,i,a,5,o,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduSkodaModel pojazduYetiWersja1.2 TSI 4x2 EasyRok produkcji2014Przebieg217 789 kmPojemność skokowa1 197 cm3Rodzaj paliwaBenzynaMoc105 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie W Mieście7 l/100kmTyp nadwoziaSUVLiczba drzwi5Liczba miejsc5KolorBrązowyRodzaj koloruMetalikKraj pochodzeniaNiemcyBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,B,ł,W,/,U,L,5,A,ż
0,Prywatne,Skoda,Yeti,SUV,,NaN,2014,217 789 km,NaN,105 KM,...,,e,a,,1,,i,,,y

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduAudiModel pojazduA7Wersja2.0 TFSI Quattro S tronicGeneracjaC7 (2011-2018)Rok produkcji2017Przebieg57 000 kmPojemność skokowa1 984 cm3Rodzaj paliwaBenzynaMoc252 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie W Mieście8 l/100kmTyp nadwoziaKompaktLiczba drzwi5Liczba miejsc5KolorSrebrnyKraj pochodzeniaPolskaStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ę,4,(,ł,),/,L,U,ś,ą
0,Prywatne,Audi,A7,Kompakt,C7 (2011-2018),NaN,2017,57 000 km,NaN,252 KM,...,d,,s,o,S,1,i,ż,w,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduToyotaModel pojazduTacomaRok produkcji2013Przebieg191 000 kmPojemność skokowa3 956 cm3Rodzaj paliwaBenzyna+LPGMoc245 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany ręcznie)Typ nadwoziaSUVLiczba drzwi4Liczba miejsc4KolorSrebrnyRodzaj koloruMetalikKraj pochodzeniaKanadaZarejestrowany w PolsceTakTuningTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,A,ę,4,(,ą,),U,L,b,ż
0,Prywatne,Toyota,Tacoma,SUV,,NaN,2013,191 000 km,NaN,245 KM,...,u,c,,d,c,T,,i,r,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduJeepModel pojazduGrand CherokeeWersjaGr 5.7 V8 SummitGeneracjaIV (2010-2021)Rok produkcji2020Przebieg35 000 kmPojemność skokowa5 654 cm3Rodzaj paliwaBenzynaMoc352 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie Poza Miastem9.0 l/100kmSpalanie W Mieście19 l/100kmTyp nadwoziaSUVEmisja CO2304 g/kmLiczba drzwi5Liczba miejsc5KolorCzerwonyKraj pochodzeniaStany ZjednoczoneData pierwszej rejestracji w historii pojazdustyczeń 2020Numer rejestracyjny pojazduBI159HHZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ś,/,U,E,L,h,ń,H,Z,ż
0,Prywatne,Jeep,Grand Cherokee,SUV,IV (2010-2021),NaN,2020,35 000 km,NaN,352 KM,...,c,k,,m,i,i,,,a,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduRenaultModel pojazduClioWersja1.2 16V AlizeGeneracjaIII (2005-2012)Rok produkcji2011Przebieg140 000 kmPojemność skokowa1 149 cm3Rodzaj paliwaBenzyna+LPGMoc75 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście7 l/100kmTyp nadwoziaAuta miejskieEmisja CO2139 g/kmLiczba drzwi5Liczba miejsc5KolorSzaryData pierwszej rejestracji w historii pojazdu05 maj 2011Numer rejestracyjny pojazduwwStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,K,g,ę,.,/,A,E,s,h,ż
0,Prywatne,Renault,Clio,Auta miejskie,III (2005-2012),NaN,2011,140 000 km,NaN,75 KM,...,,ó,d,0,k,u,m,t,i,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduBMWModel pojazduX4WersjaxM40dGeneracjaG02 (2018-)Rok produkcji2019Przebieg122 000 kmPojemność skokowa2 993 cm3Rodzaj paliwaDieselMoc326 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany automatycznie)Spalanie Poza Miastem5.0 l/100kmSpalanie W Mieście7 l/100kmTyp nadwoziaSUVEmisja CO2170 g/kmLiczba drzwi5Liczba miejsc5KolorBiałyOkres gwarancji producenta28 Kwietnia 2024lub do (przebieg km)200 000 kmKraj pochodzeniaCzechy Pierwszy właściciel (od nowości)TakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ą,),l,s,5,7,C,B,h,ż
0,Prywatne,BMW,X4,SUV,G02 (2018-),NaN,2019,122 000 km,NaN,326 KM,...,c,T,,z,,,z,i,y,y

https://www.otomoto.pl/osobowe
gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduMitsubishiModel pojazduOutlanderWersja2.4 Intense (lea)GeneracjaI (2001-2006)Rok produkcji2003Przebieg141 170 kmPojemność skokowa2 378 cm3Rodzaj paliwaBenzyna+LPGMoc160 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaSpalanie Poza Miastem8.0 l/100kmSpalanie W Mieście13 l/100kmTyp nadwoziaSUVLiczba drzwi5Liczba miejsc5KolorCzerwonyData pierwszej rejestracji w historii pojazdu10 październik 2003Numer rejestracyjny pojazduWR7022FZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,L,G,ł,/,U,5,D,ź,7,K
0,Prywatne,Mitsubishi,Outlander,SUV,I (2001-2006),NaN,2003,141 170 km,NaN,160 KM,...,i,,a,1,ż,,a,d,0,u

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduPeugeotModel pojazdu3008Wersja2.0 BlueHDi GT S&S EAT8GeneracjaII (2016-)Rok produkcji2018Przebieg128 000 kmPojemność skokowa1 997 cm3Rodzaj paliwaDieselMoc180 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaTyp nadwoziaSUVLiczba drzwi5Liczba miejsc5KolorNiebieskiRodzaj koloruMetalikKraj pochodzeniaLuksemburgData pierwszej rejestracji w historii pojazdu11 październik 2018Numer rejestracyjny pojazduxBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,p,w,b,ł,U,L,5,h,A,ż
0,Prywatne,Peugeot,3008,SUV,II (2016-),NaN,2018,128 000 km,NaN,180 KM,...,a,i,u,a,,u,,i,,y

gej 1
SzczegółyOferta odFirmaPokaż oferty z numerem VINTakMarka pojazduOpelModel pojazduCrossland XWersja1.2 T 120 Lat S&SRok produkcji2020Przebieg35 000 kmPojemność skokowa1 199 cm3Rodzaj paliwaBenzynaMoc110 KMSkrzynia biegówManualnaNapędNa przednie kołaTyp nadwoziaKompaktLiczba drzwi5Liczba miejsc5KolorNiebieskiRodzaj koloruMetalikMożliwość finansowaniaTakFaktura VATTakLeasingTakKraj pochodzeniaNiemcy Pierwszy właściciel (od nowości)TakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,K,g,ę,5,N,f,),A,V,I
0,Firma,Opel,Crossland X,Kompakt,,NaN,2020,35 000 km,NaN,110 KM,...,o,ó,d,,i,i,T,,,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduNissanModel pojazduAlmeraWersjaII 1.5 VisiaGeneracjaN16 (2000-2006)Rok produkcji2006Przebieg207 070 kmPojemność skokowa1 497 cm3Rodzaj paliwaBenzynaMoc98 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem5.0 l/100kmSpalanie W Mieście8 l/100kmTyp nadwoziaAuta małeEmisja CO2158 g/kmLiczba drzwi5Liczba miejsc5KolorBłękitnyData pierwszej rejestracji w historii pojazdu16 marzec 2006Numer rejestracyjny pojazduPZ212LEZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,8,C,K,B,ę,h,L,E,Z,ż
0,Prywatne,Nissan,Almera,Auta małe,N16 (2000-2006),NaN,2006,207 070 km,NaN,98 KM,...,,,o,ł,k,i,,,a,y

gej 1
SzczegółyOferta odFirmaMarka pojazduVolkswagenModel pojazduID.BuzzRok produkcji2023Przebieg10 kmRodzaj paliwaElektrycznyMoc204 KMSkrzynia biegówAutomatycznaPojemność baterii77 kWhTyp nadwoziaMinivanLiczba drzwi5KolorBiałyKraj pochodzeniaPolskaBezwypadkowyTakStanNoweKup ten pojazd na ratyOblicz

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,7,W,w,v,L,5,K,B,h,N
0,Firma,Volkswagen,ID.Buzz,Minivan,,NaN,2023,10 km,NaN,204 KM,...,,h,e,a,i,,r,e,o,o

gej 1
SzczegółyOferta odFirmaMarka pojazduVolkswagenModel pojazduCaliforniaRok produkcji2023Przebieg10 kmPojemność skokowa1 968 cm3Rodzaj paliwaDieselMoc150 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaTyp nadwoziaMinivanLiczba drzwi4Liczba miejsc4KolorSrebrnyRodzaj koloruMetalikMożliwość finansowaniaTakFaktura VATTakLeasingTakKraj pochodzeniaPolskaBezwypadkowyTakSerwisowany w ASOTakStanNoweKup ten pojazd na ratyOblicz

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,v,L,4,ś,T,A,g,K,h,B
0,Firma,Volkswagen,California,Minivan,,NaN,2023,10 km,NaN,150 KM,...,a,e,,ć,a,,,r,o,e

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduMercedes-BenzModel pojazduKlasa GGeneracjaW463 (1989-2017)Rok produkcji2010Przebieg246 900 kmPojemność skokowa2 987 cm3Rodzaj paliwaDieselMoc211 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany automatycznie)Typ nadwoziaSUVLiczba drzwi5Liczba miejsc2KolorBiałyData pierwszej rejestracji w historii pojazdu07 październik 2010Zarejestrowany w PolsceTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ą,),U,L,5,ł,s,h,Z,ż
0,Prywatne,Mercedes-Benz,Klasa G,SUV,W463 (1989-2017),NaN,2010,246 900 km,NaN,211 KM,...,c,T,,i,,y,c,i,a,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduAudiModel pojazduA6 AllroadWersja3.0 TDI Quattro TiptrGeneracjaC7 (2012-)Rok produkcji2014Przebieg211 000 kmPojemność skokowa2 967 cm3Rodzaj paliwaDieselMoc320 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie Poza Miastem5.0 l/100kmSpalanie W Mieście7 l/100kmTyp nadwoziaKombiLiczba drzwi5Liczba miejsc5KolorBiałyRodzaj koloruPerłowyKraj pochodzeniaPolskaZarejestrowany w PolsceTakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN13 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,/,W,K,L,5,ł,ż,3,h,ą
0,Prywatne,Audi,A6 Allroad,Kombi,C7 (2012-),NaN,2014,211 000 km,NaN,320 KM,...,1,,o,i,,y,y,,,

gej 1
SzczegółyOferta odFirmaMarka pojazduVolkswagenModel pojazduMultivanWersja6.1 2.0 TDI L1 Highline DSGRok produkcji2024Przebieg10 kmPojemność skokowa1 968 cm3Rodzaj paliwaDieselMoc204 KMSkrzynia biegówAutomatycznaNapędNa przednie kołaTyp nadwoziaMinivanLiczba drzwi5KolorCzerwonyBezwypadkowyTakStanNoweKup ten pojazd na ratyOblicz

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,P,b,m,ć,w,N,ł,5,K,C
0,Firma,Volkswagen,Multivan,Minivan,,NaN,2024,10 km,NaN,204 KM,...,o,l,3,,y,a,a,,u,z

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduPeugeotModel pojazduPartnerWersjaTepee BlueHDi 100 Stop&Start ActiveGeneracjaII (2008-2019)Rok produkcji2017Przebieg84 206 kmPojemność skokowa1 560 cm3Rodzaj paliwaDieselMoc99 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.1 l/100kmSpalanie W Mieście4,30 l/100kmTyp nadwoziaMinivanEmisja CO2109 g/kmLiczba drzwi5Liczba miejsc5KolorCzarnyKraj pochodzeniaBelgiaData pierwszej rejestracji w historii pojazdu02 marzec 2017Numer rejestracyjny pojazduWWL2457UZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,v,E,L,K,h,7,W,U,Z,ż
0,Prywatne,Peugeot,Partner,Minivan,II (2008-2019),NaN,2017,84 206 km,NaN,99 KM,...,a,m,2,r,o,,,,a,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduJeepModel pojazduInnyRok produkcji2021Przebieg15 000 kmPojemność skokowa3 600 cm3Rodzaj paliwaBenzynaMoc290 KMSkrzynia biegówAutomatycznaTyp nadwoziaSUVLiczba drzwi4KolorCzarnyStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,0,ś,w,3,6,R,B,9,b,ż
0,Prywatne,Jeep,Inny,SUV,,NaN,2021,15 000 km,NaN,290 KM,...,,ć,i,,0,o,e,0,i,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduFiatModel pojazduFreemontWersja2.0 Multijet Black Code AWDRok produkcji2013Przebieg288 000 kmPojemność skokowa1 956 cm3Rodzaj paliwaDieselMoc170 KMSkrzynia biegówAutomatycznaNapęd4x4 (dołączany automatycznie)Spalanie W Mieście9,60 l/100kmTyp nadwoziaSUVLiczba drzwi5Liczba miejsc7KolorCzarnyRodzaj koloruMetalikStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ę,4,(,ą,),",",s,7,C,U
0,Prywatne,Fiat,Freemont,SUV,,NaN,2013,288 000 km,NaN,170 KM,...,d,,d,c,S,6,c,,z,ż

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduMercedes-BenzModel pojazduKlasa EWersja200 BlueTEC AvantgardeGeneracjaW212 (2009-2016)Rok produkcji2010Przebieg260 500 kmPojemność skokowa2 143 cm3Rodzaj paliwaDieselMoc136 KMSkrzynia biegówManualnaNapędNa tylne kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście5 l/100kmTyp nadwoziaSedanEmisja CO2125 g/kmLiczba drzwi4Liczba miejsc5KolorSzaryRodzaj koloruMetalikKraj pochodzeniaFrancjaData pierwszej rejestracji w historii pojazdu26 lipiec 2010Numer rejestracyjny pojazduxxxxxxxxxxxxxxxxxSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,.,/,W,L,F,D,x,U,K,ś
0,Prywatne,Mercedes-Benz,Klasa E,Sedan,W212 (2009-2016),NaN,2010,260 500 km,NaN,136 KM,...,0,k,y,i,r,a,x,ż,u,w

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduMaseratiModel pojazduGranCabrioWersjaSportRok produkcji2013Przebieg108 000 kmPojemność skokowa4 691 cm3Rodzaj paliwaBenzynaMoc460 KMSkrzynia biegówAutomatycznaNapędNa tylne kołaSpalanie Poza Miastem10.0 l/100kmSpalanie W Mieście23 l/100kmTyp nadwoziaKabrioletEmisja CO2354 g/kmLiczba drzwi2Liczba miejsc4KolorCzarnyData pierwszej rejestracji w historii pojazdu20 luty 2014Numer rejestracyjny pojazduPy12345StanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ę,ł,.,/,3,C,h,U,b,ś
0,Prywatne,Maserati,GranCabrio,Kabriolet,,NaN,2013,108 000 km,NaN,460 KM,...,d,a,0,1,5,z,i,ż,l,w

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduPeugeotModel pojazdu508WersjaRXH BlueHDi 180 EAT6 Stop&StartGeneracjaI (2010-2018)Rok produkcji2013Przebieg207 000 kmPojemność skokowa1 997 cm3Rodzaj paliwaDieselMoc180 KMSkrzynia biegówAutomatycznaSpalanie W Mieście5,20 l/100kmUszkodzonyTakTyp nadwoziaKombiLiczba drzwi5Liczba miejsc5KolorBłękitnyStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,w,8,b,ś,5,/,K,ę,U,W
0,Prywatne,Peugeot,508,Kombi,I (2010-2018),NaN,2013,207 000 km,NaN,180 KM,...,a,0,l,w,,1,u,k,ż,y

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduDaciaModel pojazduLodgyWersja1.5 dCi Stepway S&S EU6Rok produkcji2017Przebieg140 125 kmPojemność skokowa1 461 cm3Rodzaj paliwaDieselMoc107 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem3.0 l/100kmSpalanie W Mieście4 l/100kmTyp nadwoziaMinivanEmisja CO2105 g/kmLiczba drzwi5Liczba miejsc7KolorNiebieskiRodzaj koloruMetalikKraj pochodzeniaFrancjaData pierwszej rejestracji w historii pojazdu13 grudzień 2017Numer rejestracyjny pojazduRZ187CRZarejestrowany w PolsceTakBezwypadkowyTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ł,3,ś,C,5,7,h,ń,B,ą
0,Prywatne,Dacia,Lodgy,Minivan,,NaN,2017,140 125 km,NaN,107 KM,...,o,.,w,,,,i,,e,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduFordModel pojazduFiestaWersja1.25 AmbienteGeneracjaMk7 (2008-)Rok produkcji2013Przebieg145 000 kmPojemność skokowa1 242 cm3Rodzaj paliwaBenzynaMoc82 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście6 l/100kmTyp nadwoziaKompaktEmisja CO2120 g/kmLiczba drzwi5Liczba miejsc5KolorZłotyRodzaj koloruMetalikKraj pochodzeniaFrancjaBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,ś,6,C,5,K,Z,R,h,A,ż
0,Prywatne,Ford,Fiesta,Kompakt,Mk7 (2008-),NaN,2013,145 000 km,NaN,82 KM,...,c,,,,r,ł,o,o,,y

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduAlfa RomeoModel pojazduMitoWersja1.3 JTDM Distinctive S&SRok produkcji2011Przebieg249 000 kmPojemność skokowa1 248 cm3Rodzaj paliwaDieselMoc95 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem2.9 l/100kmSpalanie W Mieście4,40 l/100kmTyp nadwoziaAuta miejskieEmisja CO290 g/kmLiczba drzwi3Liczba miejsc4KolorNiebieskiRodzaj koloruMetalikZarejestrowany w PolsceTakBezwypadkowyTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,8,l,ł,4,/,g,B,U,V,ą
0,Firma,Alfa Romeo,Mito,Auta miejskie,,NaN,2011,249 000 km,NaN,95 KM,...,,i,o,,1,ó,e,ż,,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduAudiModel pojazduA8Wersja3.0 TDI QuattroGeneracjaD4 (2010-)Rok produkcji2011Przebieg291 000 kmPojemność skokowa2 967 cm3Rodzaj paliwaDieselMoc250 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Spalanie Poza Miastem5.0 l/100kmSpalanie W Mieście8 l/100kmTyp nadwoziaSedanEmisja CO2174 g/kmLiczba drzwi4Liczba miejsc5KolorZłotyRodzaj koloruMatowyZarejestrowany w PolsceTakBezwypadkowyTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,W,E,7,L,ł,Z,B,U,K,ś
0,Prywatne,Audi,A8,Sedan,D4 (2010-),NaN,2011,291 000 km,NaN,250 KM,...,y,m,4,i,o,a,e,ż,u,w

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduFordModel pojazduFocusWersjaTurnier 1.6 TDCi DPF Start-Stopp-System TitaniumGeneracjaMk3 (2010-2018)Rok produkcji2014Przebieg153 000 kmPojemność skokowa1 560 cm3Rodzaj paliwaDieselMoc115 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem3.7 l/100kmSpalanie W Mieście5,10 l/100kmTyp nadwoziaKombiEmisja CO2109 g/kmLiczba drzwi5Liczba miejsc5KolorSzaryRodzaj koloruPerłowyKraj pochodzeniaNiemcyBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,b,ł,7,ś,/,K,E,L,A,ż
0,Prywatne,Ford,Focus,Kombi,Mk3 (2010-2018),NaN,2014,153 000 km,NaN,115 KM,...,a,o,,c,k,o,m,i,,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduOpelModel pojazduCorsaGeneracjaC (2000-2006)Rok produkcji2006Przebieg244 952 kmPojemność skokowa998 cm3Rodzaj paliwaBenzynaMoc60 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.0 l/100kmSpalanie W Mieście6 l/100kmTyp nadwoziaAuta miejskieEmisja CO2120 g/kmLiczba drzwi3Liczba miejsc5KolorSrebrnyStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,s,9,w,6,b,ł,1,ś,K,ż
0,Prywatne,Opel,Corsa,Auta miejskie,C (2000-2006),NaN,2006,244 952 km,NaN,60 KM,...,c,8,i,,i,a,2,c,o,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduCitroënModel pojazduC4 PicassoGeneracjaI (2006-2013)Rok produkcji2012Przebieg146 000 kmPojemność skokowa1 560 cm3Rodzaj paliwaDieselMoc110 KMSkrzynia biegówManualnaNapędNa przednie kołaTyp nadwoziaKompaktLiczba drzwi5Liczba miejsc5KolorBiałyRodzaj koloruMetalikData pierwszej rejestracji w historii pojazdu05 wrzesień 2012Numer rejestracyjny pojazdu1DVB408StanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,K,L,5,h,ń,D,B,U,W,ś
0,Prywatne,Citroën,C4 Picasso,Kompakt,I (2006-2013),NaN,2012,146 000 km,NaN,110 KM,...,u,i,,i,,,4,ż,y,w

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduHondaModel pojazduCivicWersja2.2i-CTDi SportGeneracjaVIII (2006-2011)Rok produkcji2010Przebieg210 000 kmPojemność skokowa2 204 cm3Rodzaj paliwaDieselMoc140 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.5 l/100kmSpalanie W Mieście6,70 l/100kmTyp nadwoziaKompaktEmisja CO2140 g/kmLiczba drzwi5Liczba miejsc5KolorCzerwonyRodzaj koloruMetalikKraj pochodzeniaBelgiaZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,b,ł,5,ś,7,/,L,h,f,ą
0,Firma,Honda,Civic,Kompakt,VIII (2006-2011),NaN,2010,210 000 km,NaN,140 KM,...,a,y,,c,0,k,i,,i,

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduCitroënModel pojazduC4 PicassoWersja2.0 BlueHDi ExclusiveGeneracjaII (2013-)Rok produkcji2014Przebieg200 000 kmPojemność skokowa1 997 cm3Rodzaj paliwaDieselMoc150 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem3.0 l/100kmSpalanie W Mieście4 l/100kmTyp nadwoziaMinivanEmisja CO2110 g/kmLiczba drzwi5Liczba miejsc7KolorBrązowyRodzaj koloruPerłowyLeasingTakData pierwszej rejestracji w historii pojazdu05 maj 2014Numer rejestracyjny pojazduWO84988Zarejestrowany w PolsceTakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,C,7,K,ą,R,L,D,8,Z,U
0,Prywatne,Citroën,C4 Picasso,Minivan,II (2013-),NaN,2014,200 000 km,NaN,150 KM,...,,,u,z,o,e,a,,a,ż

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduSkodaModel pojazduPraktikRok produkcji2014Przebieg269 000 kmPojemność skokowa1 598 cm3Rodzaj paliwaDieselMoc90 KMSkrzynia biegówManualnaTyp nadwoziaMinivanLiczba drzwi5Liczba miejsc2KolorBiałyRodzaj koloruMetalikStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,w,1,5,8,3,D,s,K,B,ż
0,Prywatne,Skoda,Praktik,Minivan,,NaN,2014,269 000 km,NaN,90 KM,...,i,,9,,,i,c,o,i,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduBMWModel pojazduSeria 1Wersja116d EfficientDynamicsGeneracjaF20/F21 (2011-)Rok produkcji2015Przebieg174 000 kmPojemność skokowa1 496 cm3Rodzaj paliwaDieselMoc116 KMSkrzynia biegówManualnaNapędNa tylne kołaSpalanie Poza Miastem3.0 l/100kmSpalanie W Mieście3 l/100kmTyp nadwoziaKompaktEmisja CO289 g/kmLiczba drzwi5Liczba miejsc5KolorSrebrnyRodzaj koloruMetalikKraj pochodzeniaBelgiaData pierwszej rejestracji w historii pojazdu10 listopad 2015Numer rejestracyjny pojazdulu638nlStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,g,ę,l,ł,C,8,L,B,h,ż
0,Prywatne,BMW,Seria 1,Kompakt,F20/F21 (2011-),NaN,2015,174 000 km,NaN,116 KM,...,ó,d,,a,,n,i,e,i,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduRenaultModel pojazduMeganeGeneracjaII (2002-2008)Rok produkcji2007Przebieg130 000 kmPojemność skokowa1 998 cm3Rodzaj paliwaBenzynaMoc134 KMSkrzynia biegówManualnaTyp nadwoziaKabrioletLiczba drzwi3Liczba miejsc4KolorCzarnyStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,w,9,3,B,s,4,K,C,U,W
0,Prywatne,Renault,Megane,Kabriolet,II (2002-2008),NaN,2007,130 000 km,NaN,134 KM,...,a,9,4,e,c,,u,z,ż,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMarka pojazduVolkswagenModel pojazduPassatWersja2.0 TDI ComfortlineGeneracjaB7 (2010-2014)Rok produkcji2013Przebieg268 000 kmPojemność skokowa1 968 cm3Rodzaj paliwaDieselMoc140 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie W Mieście5 l/100kmTyp nadwoziaKombiLiczba drzwi5KolorBiałyKraj pochodzeniaNiemcyData pierwszej rejestracji w historii pojazdu19 wrzesień 2013Zarejestrowany w PolsceTakBezwypadkowyTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,w,9,K,g,ę,5,ł,h,ń,ż
0,Prywatne,Volkswagen,Passat,Kombi,B7 (2010-2014),NaN,2013,268 000 km,NaN,140 KM,...,i,6,,ó,d,,y,i,,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduInfinitiModel pojazduFXGeneracjaII (2009-2013)Rok produkcji2009Przebieg130 776 kmPojemność skokowa5 026 cm3Rodzaj paliwaBenzynaMoc390 KMSkrzynia biegówAutomatycznaNapęd4x4 (stały)Typ nadwoziaSUVLiczba drzwi5Liczba miejsc5KolorCzarnyRodzaj koloruMetalikData pierwszej rejestracji w historii pojazdu23 marzec 2011Numer rejestracyjny pojazduRZE 57436Zarejestrowany w PolsceTak Pierwszy właściciel (od nowości)TakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,b,5,R,D,Z,E,6,ś,B,W
0,Prywatne,Infiniti,FX,SUV,II (2009-2013),NaN,2009,130 776 km,NaN,390 KM,...,l,7,,a,a,,,w,e,y

gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduPeugeotModel pojazdu307 CCWersja2.0Rok produkcji2003Przebieg172 500 kmPojemność skokowa1 997 cm3Rodzaj paliwaBenzynaMoc138 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem6.0 l/100kmSpalanie W Mieście11 l/100kmTyp nadwoziaKabrioletLiczba drzwi2KolorSrebrnyRodzaj koloruMetalikStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,9,B,l,ł,s,6,/,K,L,ż
0,Prywatne,Peugeot,307 CC,Kabriolet,,NaN,2003,172 500 km,NaN,138 KM,...,9,e,,a,t,.,1,o,i,y

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduPorscheModel pojazdu911WersjaCarrera GTS CabrioGeneracja992 (2019-)Rok produkcji2023Przebieg9 900 kmPojemność skokowa2 981 cm3Rodzaj paliwaBenzynaMoc480 KMSkrzynia biegówAutomatycznaNapędNa tylne kołaSpalanie Poza Miastem7.0 l/100kmSpalanie W Mieście13 l/100kmTyp nadwoziaKabrioletEmisja CO2224 g/kmLiczba drzwi2Liczba miejsc4KolorGranatowyRodzaj koloruMetalikOkres gwarancji producenta13 Kwietnia 2025Kraj pochodzeniaPolskaData pierwszej rejestracji w historii pojazdu13 kwiecień 2023Numer rejestracyjny pojazduSK911WVZarejestrowany w PolsceTak Pierwszy właściciel (od nowości)TakBezwypadkowyTakSerwisowany w ASOTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,/,l,C,4,g,ń,ł,(,U,ą
0,Prywatne,Porsche,911,Kabriolet,992 (2019-),NaN,2023,9 900 km,NaN,480 KM,...,1,,,,ó,,o,o,ż,

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduRenaultModel pojazduMeganeWersja1.5 dCi LimitedGeneracjaIII (2008-2016)Rok produkcji2014Przebieg118 000 kmPojemność skokowa1 461 cm3Rodzaj paliwaDieselMoc110 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem3.0 l/100kmSpalanie W Mieście4 l/100kmTyp nadwoziaKompaktEmisja CO295 g/kmLiczba drzwi5Liczba miejsc5KolorSzaryData pierwszej rejestracji w historii pojazdu18 lipiec 2014Numer rejestracyjny pojazduKRA 146CEStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,3,g,ę,.,/,s,ż,h,ł,ą
0,Prywatne,Renault,Megane,Kompakt,III (2008-2016),NaN,2014,118 000 km,NaN,110 KM,...,,/,d,0,1,t,y,,y,

https://www.otomoto.pl/osobowe?page=2
https://www.otomoto.pl/osobowe?page=2
gej 1
SzczegółyOferta odPrywatnePokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduCitroënModel pojazduC4 PicassoGeneracjaI (2006-2013)Rok produkcji2012Przebieg146 000 kmPojemność skokowa1 560 cm3Rodzaj paliwaDieselMoc110 KMSkrzynia biegówManualnaNapędNa przednie kołaTyp nadwoziaKompaktLiczba drzwi5Liczba miejsc5KolorBiałyRodzaj koloruMetalikData pierwszej rejestracji w historii pojazdu05 wrzesień 2012Numer rejestracyjny pojazdu1DVB408StanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,K,L,5,h,ń,D,B,U,W,ś
0,Prywatne,Citroën,C4 Picasso,Kompakt,I (2006-2013),NaN,2012,146 000 km,NaN,110 KM,...,u,i,,i,,,4,ż,y,w

gej 1
SzczegółyZWERYFIKOWANE DANEOferta odFirmaPokaż oferty z numerem VINTakMa numer rejestracyjnyTakMarka pojazduHondaModel pojazduCivicWersja2.2i-CTDi SportGeneracjaVIII (2006-2011)Rok produkcji2010Przebieg210 000 kmPojemność skokowa2 204 cm3Rodzaj paliwaDieselMoc140 KMSkrzynia biegówManualnaNapędNa przednie kołaSpalanie Poza Miastem4.5 l/100kmSpalanie W Mieście6,70 l/100kmTyp nadwoziaKompaktEmisja CO2140 g/kmLiczba drzwi5Liczba miejsc5KolorCzerwonyRodzaj koloruMetalikKraj pochodzeniaBelgiaZarejestrowany w PolsceTakStanUżywaneKup ten pojazd na ratyObliczVINWyświetl VIN14 pól zweryfikowanychSzczegółowe dane pojazdu zostały zweryfikowane poprzez porównanie ich z rządową bazą danych

,Oferta od,Marka pojazdu,Model pojazdu,Typ nadwozia,Generacja,KolorRodzaj koloru,Rok produkcji,Przebieg,Pojemność skokowaRodzaj paliwa,Moc,...,b,ł,5,ś,7,/,L,h,f,ą
0,Firma,Honda,Civic,Kompakt,VIII (2006-2011),NaN,2010,210 000 km,NaN,140 KM,...,a,y,,c,0,k,i,,i,

gej 1

KeyboardInterrupt: